In [40]:
import pandas as pd
import numpy as np
from sklearn_extra.cluster import KMedoids

In [42]:
u = pd.read_csv('data/usersSim.csv')
u = u.drop(columns = ['Unnamed: 0'])
u

,0,1,2,3,4,5,6,7,8,9,...,161,162,163,164,165,166,167,168,169,170
0,1.000000,0.506610,0.408813,0.408813,0.804406,0.604406,0.702203,0.304406,0.902203,0.504406,...,0.000000,0.706610,0.706610,0.604406,0.804406,0.902203,0.902203,0.506610,0.902203,1.000000
1,0.506610,1.000000,0.902203,0.902203,0.702203,0.902203,0.608813,0.602203,0.604406,0.402203,...,0.406610,0.800000,0.800000,0.902203,0.702203,0.604406,0.604406,1.000000,0.604406,0.506610
2,0.408813,0.902203,1.000000,1.000000,0.604406,0.804406,0.511016,0.504406,0.506610,0.304406,...,0.504406,0.702203,0.702203,0.804406,0.604406,0.506610,0.506610,0.902203,0.506610,0.408813
3,0.408813,0.902203,1.000000,1.000000,0.604406,0.804406,0.511016,0.504406,0.506610,0.304406,...,0.504406,0.702203,0.702203,0.804406,0.604406,0.506610,0.506610,0.902203,0.506610,0.408813
4,0.804406,0.702203,0.604406,0.604406,1.000000,0.800000,0.506610,0.500000,0.902203,0.700000,...,0.108813,0.902203,0.902203,0.800000,1.000000,0.902203,0.902203,0.702203,0.902203,0.804406
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,0.902203,0.604406,0.506610,0.506610,0.902203,0.702203,0.604406,0.402203,1.000000,0.602203,...,0.011016,0.804406,0.804406,0.702203,0.902203,1.000000,1.000000,0.604406,1.000000,0.902203
167,0.902203,0.604406,0.506610,0.506610,0.902203,0.702203,0.604406,0.402203,1.000000,0.602203,...,0.011016,0.804406,0.804406,0.702203,0.902203,1.000000,1.000000,0.604406,1.000000,0.902203
168,0.506610,1.000000,0.902203,0.902203,0.702203,0.902203,0.608813,0.602203,0.604406,0.402203,...,0.406610,0.800000,0.800000,0.902203,0.702203,0.604406,0.604406,1.000000,0.604406,0.506610
169,0.902203,0.604406,0.506610,0.506610,0.902203,0.702203,0.604406,0.402203,1.000000,0.602203,...,0.011016,0.804406,0.804406,0.702203,0.902203,1.000000,1.000000,0.604406,1.000000,0.902203
170,1.000000,0.506610,0.408813,0.408813,0.804406,0.604406,0.702203,0.304406,0.902203,0.504406,...,0.000000,0.706610,0.706610,0.604406,0.804406,0.902203,0.902203,0.506610,0.902203,1.000000

In [43]:
kmedoids = KMedoids(init='random', n_clusters= 10, metric="precomputed", random_state=123,max_iter=100000)
kmedoids.fit(u)

c:\users\alberto\appdata\local\programs\python\python39\lib\site-packages\sklearn_extra\cluster\_k_medoids.py:275: UserWarning: Cluster 4 is empty! self.labels_[self.medoid_indices_[4]] may not be labeled with its corresponding cluster (4).
  warnings.warn(
c:\users\alberto\appdata\local\programs\python\python39\lib\site-packages\sklearn_extra\cluster\_k_medoids.py:275: UserWarning: Cluster 7 is empty! self.labels_[self.medoid_indices_[7]] may not be labeled with its corresponding cluster (7).
  warnings.warn(
c:\users\alberto\appdata\local\programs\python\python39\lib\site-packages\sklearn_extra\cluster\_k_medoids.py:275: UserWarning: Cluster 9 is empty! self.labels_[self.medoid_indices_[9]] may not be labeled with its corresponding cluster (9).
  warnings.warn(
c:\users\alberto\appdata\local\programs\python\python39\lib\site-packages\sklearn_extra\cluster\_k_medoids.py:275: UserWarning: Cluster 0 is empty! self.labels_[self.medoid_indices_[0]] may not be labeled with its corresponding cluster (0).
  warnings.warn(
c:\users\alberto\appdata\local\programs\python\python39\lib\site-packages\sklearn_extra\cluster\_k_medoids.py:275: UserWarning: Cluster 3 is empty! self.labels_[self.medoid_indices_[3]] may not be labeled with its corresponding cluster (3).
  warnings.warn(
c:\users\alberto\appdata\local\programs\python\python39\lib\site-packages\sklearn_extra\cluster\_k_medoids.py:275: UserWarning: Cluster 8 is empty! self.labels_[self.medoid_indices_[8]] may not be labeled with its corresponding cluster (8).
  warnings.warn(
c:\users\alberto\appdata\local\programs\python\python39\lib\site-packages\sklearn_extra\cluster\_k_medoids.py:275: UserWarning: Cluster 2 is empty! self.labels_[self.medoid_indices_[2]] may not be labeled with its corresponding cluster (2).
  warnings.warn(
c:\users\alberto\appdata\local\programs\python\python39\lib\site-packages\sklearn_extra\cluster\_k_medoids.py:275: UserWarning: Cluster 1 is empty! self.labels_[self.medoid_indices_[1]] may not be labeled with its corresponding cluster (1).
  warnings.warn(
c:\users\alberto\appdata\local\programs\python\python39\lib\site-packages\sklearn_extra\cluster\_k_medoids.py:275: UserWarning: Cluster 5 is empty! self.labels_[self.medoid_indices_[5]] may not be labeled with its corresponding cluster (5).
  warnings.warn(
c:\users\alberto\appdata\local\programs\python\python39\lib\site-packages\sklearn_extra\cluster\_k_medoids.py:243: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(

KMedoids(init='random', max_iter=100000, metric='precomputed', n_clusters=10,
         random_state=123)

In [45]:
import matplotlib.pyplot as plt
import seaborn as sns

In [49]:
aux = pd.read_csv("data/Prado_users.csv")
aux.drop('userId', axis=1, inplace=True) 
aux['cluster'] = kmedoids.labels_

In [50]:
aux

       age  gender country  cluster
0    55-64    male   Spain        6
1    25-34  female   Spain        1
2    18-24  female   Spain        1
3    18-24  female   Spain        1
4    35-44    male   Spain        0
..     ...     ...     ...      ...
166  45-54    male   Italy        6
167  45-54    male   Spain        6
168  25-34  female   Spain        1
169  45-54    male   Spain        6
170  55-64    male   Spain        6

[171 rows x 4 columns]

In [51]:
sns.pairplot(aux,hue = 'cluster')
plt.show()

ValueError: No variables found for grid columns.

In [44]:
kmedoids.labels_

array([6, 1, 1, 1, 0, 6, 6, 9, 6, 0, 6, 6, 0, 0, 1, 0, 6, 6, 6, 6, 6, 6,
       0, 1, 0, 6, 6, 0, 6, 1, 0, 6, 6, 0, 0, 9, 0, 1, 6, 6, 6, 6, 6, 0,
       1, 0, 1, 0, 2, 0, 0, 0, 9, 6, 0, 1, 0, 1, 6, 6, 0, 0, 0, 0, 0, 0,
       6, 6, 6, 6, 6, 0, 0, 6, 6, 1, 1, 6, 6, 2, 6, 6, 1, 6, 0, 0, 0, 0,
       0, 1, 6, 6, 6, 6, 0, 6, 0, 6, 9, 1, 0, 0, 6, 4, 0, 6, 6, 6, 0, 6,
       6, 1, 6, 1, 0, 6, 0, 0, 6, 6, 6, 0, 0, 6, 0, 6, 0, 0, 0, 0, 1, 0,
       6, 6, 6, 0, 0, 9, 6, 0, 1, 6, 0, 0, 0, 6, 4, 0, 1, 0, 6, 9, 4, 1,
       0, 6, 6, 6, 0, 6, 0, 0, 0, 0, 6, 0, 6, 6, 1, 6, 6], dtype=int64)

In [36]:
label = aux['cluster']
label = label.to_list()
print(label)
# label

[6, 1, 1, 1, 0, 6, 6, 9, 6, 0, 6, 6, 0, 0, 1, 0, 6, 6, 6, 6, 6, 6, 0, 1, 0, 6, 6, 0, 6, 1, 0, 6, 6, 0, 0, 9, 0, 1, 6, 6, 6, 6, 6, 0, 1, 0, 1, 0, 2, 0, 0, 0, 9, 6, 0, 1, 0, 1, 6, 6, 0, 0, 0, 0, 0, 0, 6, 6, 6, 6, 6, 0, 0, 6, 6, 1, 1, 6, 6, 2, 6, 6, 1, 6, 0, 0, 0, 0, 0, 1, 6, 6, 6, 6, 0, 6, 0, 6, 9, 1, 0, 0, 6, 4, 0, 6, 6, 6, 0, 6, 6, 1, 6, 1, 0, 6, 0, 0, 6, 6, 6, 0, 0, 6, 0, 6, 0, 0, 0, 0, 1, 0, 6, 6, 6, 0, 0, 9, 6, 0, 1, 6, 0, 0, 0, 6, 4, 0, 1, 0, 6, 9, 4, 1, 0, 6, 6, 6, 0, 6, 0, 0, 0, 0, 6, 0, 6, 6, 1, 6, 6]

In [39]:
# u_labels = np.unique(label)
 
# #plotting the results:
 
# for i in u_labels:
#     plt.scatter(aux[label == i , 0] , aux[label == i , 1] , label = i)
# plt.legend()
# plt.show()

TypeError: '(array([False, False, False, False,  True, False, False, False, False,
        True, False, False,  True,  True, False,  True, False, False,
       False, False, False, False,  True, False,  True, False, False,
        True, False, False,  True, False, False,  True,  True, False,
        True, False, False, False, False, False, False,  True, False,
        True, False,  True, False,  True,  True,  True, False, False,
        True, False,  True, False, False, False,  True,  True,  True,
        True,  True,  True, False, False, False, False, False,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True, False,
       False, False, False, False,  True, False,  True, False, False,
       False,  True,  True, False, False,  True, False, False, False,
        True, False, False, False, False, False,  True, False,  True,
        True, False, False, False,  True,  True, False,  True, False,
        True,  True,  True,  True, False,  True, False, False, False,
        True,  True, False, False,  True, False, False,  True,  True,
        True, False, False,  True, False,  True, False, False, False,
       False,  True, False, False, False,  True, False,  True,  True,
        True,  True, False,  True, False, False, False, False, False]), 0)' is an invalid key